sudo: required
services:
    -docker

before_install:
    - docker build -t mail2santhoshasokan/docker-react -f DockerFile.dev .


script:
    - docker run -e CI=true mail2santhoshasokan/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-841806388742"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
