sudo: required
services:
    - docker

before_install:
    - docker build -t mail2santhoshasokan/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true mail2santhoshasokan/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-833385162024"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

